# For public, HTTPS servers.
version: '2.2'

services:
  postgres:
    extends:
      file: docker-compose.backend.template.yml
      service: postgres
    environment:
      - KOBO_POSTGRES_DB_SERVER_ROLE=primary
    networks:
      kobo-be-network:
        aliases:
          - postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on: 
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=sysadmin@agape.dev
      - PGADMIN_DEFAULT_PASSWORD=!Sunshine1
    ports:
      - 8001:80
    networks:
      kobo-be-network:
        aliases:
          - pgadmin4

  mongo:
    extends:
      file: docker-compose.backend.template.yml
      service: mongo
    networks:
      kobo-be-network:

  redis_main:
    extends:
      file: docker-compose.backend.template.yml
      service: redis_main
    environment:
      - KOBO_REDIS_SERVER_ROLE=main
    networks:
      kobo-be-network:

  redis_cache:
    extends:
      file: docker-compose.backend.template.yml
      service: redis_cache
    environment:
      - KOBO_REDIS_SERVER_ROLE=cache
    networks:
      kobo-be-network:

networks:
  kobo-be-network:
    driver: bridge
